/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/ball.glb 
Author: MaggaModels (https://sketchfab.com/MaggaModels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beach-ball-25e1816c0e22444bb62816d3999d1b0b
Title: Beach Ball
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Ball(props) {
  const { nodes, materials } = useGLTF("models/ball.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Sphere_yellow_0.geometry}
            material={materials.yellow}
          />
          <mesh
            geometry={nodes.Sphere_white_0.geometry}
            material={materials.white}
          />
          <mesh
            geometry={nodes.Sphere_red_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Sphere_blue_0.geometry}
            material={materials.blue}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/ball.glb");
