/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/minecraft_chicken.glb 
Author: Vincent Yanez (https://sketchfab.com/vinceyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-chicken-2968358f83af441db2b8e7c097f0173e
Title: Minecraft - Chicken
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Chicken(props) {
  const { nodes, materials } = useGLTF("models/minecraft_chicken.glb");
  return (
    <group {...props} dispose={null} scale={[0.1, 0.1, 0.1]}>
      <mesh
        geometry={nodes["Chicken_02_-_Default_0"].geometry}
        material={materials["02_-_Default"]}
        position={[0, 0.5, -6]}
      />
    </group>
  );
}

useGLTF.preload("models/minecraft_chicken.glb");
