/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/teste.glb 
Author: tim.time (https://sketchfab.com/timislav845455)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/5-dollars-7f1506efa065479097ef51e5ce4b1b3f
Title: 5 dollars
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Dollar(props) {
  const { nodes, materials } = useGLTF("models/teste.glb");

  return (
    <group {...props} dispose={null}>
      <group
        position={[4.299, 0, -1.985]}
        rotation={[Math.PI, -1.011, 0]}
        scale={[-1, 0.008, 2.362]}
      >
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/teste.glb");
