/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/ground.glb 
Author: polycorteams (https://sketchfab.com/polycorteams)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pillar-cap-indiana-limestonetm-5f698c7322a6425d87d4c071bb90dbd6
Title: PILLAR CAP - INDIANA LIMESTONE™
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Ground(props) {
  const { nodes, materials } = useGLTF("models/ground.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.8} position-y={-1}>
        <mesh geometry={nodes.Material2.geometry} material={materials.auto_3} />
        <lineSegments
          geometry={nodes.Material2_1.geometry}
          material={materials.edge_color000255}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/ground.glb");
