/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/Mage.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Mage(props) {
  const { animation } = props;
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/Mage.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    nodes.Spellbook.visible = false;
  }, []);

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.5).play();
    return () => actions[animation]?.fadeOut(0.5);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Rig">
          <primitive object={nodes.root} />
          <skinnedMesh
            name="Mage_ArmLeft"
            geometry={nodes.Mage_ArmLeft.geometry}
            material={materials.mage_texture}
            skeleton={nodes.Mage_ArmLeft.skeleton}
          />
          <skinnedMesh
            name="Mage_ArmRight"
            geometry={nodes.Mage_ArmRight.geometry}
            material={materials.mage_texture}
            skeleton={nodes.Mage_ArmRight.skeleton}
          />
          <skinnedMesh
            name="Mage_Body"
            geometry={nodes.Mage_Body.geometry}
            material={materials.mage_texture}
            skeleton={nodes.Mage_Body.skeleton}
          />
          <skinnedMesh
            name="Mage_Head"
            geometry={nodes.Mage_Head.geometry}
            material={materials.mage_texture}
            skeleton={nodes.Mage_Head.skeleton}
          />
          <skinnedMesh
            name="Mage_LegLeft"
            geometry={nodes.Mage_LegLeft.geometry}
            material={materials.mage_texture}
            skeleton={nodes.Mage_LegLeft.skeleton}
          />
          <skinnedMesh
            name="Mage_LegRight"
            geometry={nodes.Mage_LegRight.geometry}
            material={materials.mage_texture}
            skeleton={nodes.Mage_LegRight.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/Mage.glb");
