/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/skybox.glb 
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f
Title: FREE - SkyBox Anime Sky
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Skybox(props) {
  const { nodes, materials } = useGLTF("models/skybox.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <mesh
          geometry={nodes.Sphere__0.geometry}
          material={materials["Scene_-_Root"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50000}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/skybox.glb");
