/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/trash.glb 
Author: Raphael Escamilla (https://sketchfab.com/Raffey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/green-city-trash-can-c5d23e21daef4fc2a62704149f5f9af6
Title: Green City Trash Can
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Trash(props) {
  const { nodes, materials } = useGLTF("models/trash.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_7.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.defaultMaterial_8.geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/trash.glb");
