/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/yoshi_egg.glb 
Author: Sir2Yas (https://sketchfab.com/yas2yas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yoshi-egg-2125c39434ed4b3696bdff0a0bdb6fb2
Title: Yoshi Egg
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function YoshiEgg(props) {
  const { nodes, materials } = useGLTF("models/yoshi_egg.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cylinder004_0.geometry}
          material={materials["Material.007"]}
          position={[0.741, 0.11, -0.969]}
          rotation={[-0.106, -0.604, -2.746]}
          scale={0.602}
        />
        <mesh
          geometry={nodes.Cylinder003_0.geometry}
          material={materials["Material.005"]}
          position={[-0.867, -0.037, 1.342]}
          rotation={[-0.121, -0.762, -2.769]}
          scale={0.528}
        />
        <mesh
          geometry={nodes.Cylinder002_0.geometry}
          material={materials["Material.003"]}
          position={[-1.08, 0.317, -0.531]}
          rotation={[-0.528, -1.397, 3.076]}
          scale={1.118}
        />
        <mesh
          geometry={nodes.Cylinder001_0.geometry}
          material={materials.Material}
          position={[0.358, 0.844, 0.957]}
          rotation={[-0.948, 0.844, 2.415]}
          scale={0.773}
        />
        <mesh
          geometry={nodes.Cylinder_0.geometry}
          material={materials.Material}
          position={[0.193, -0.95, 0.557]}
          rotation={[1.509, 0, 0]}
          scale={1.127}
        />
        <mesh
          geometry={nodes.Sphere_0.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/yoshi_egg.glb");
